# syntax=docker/dockerfile:1

# Build stage: produce the Spring Boot executable (fat) jar.
# spring-boot-starter-parent declares the spring-boot-maven-plugin in
# pluginManagement, so spring-boot:repackage is invoked explicitly to turn the
# plain jar produced by `package` into an executable jar without touching pom.xml.
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN --mount=type=cache,target=/root/.m2 \
    mvn -B -e -DskipTests package spring-boot:repackage \
    && cp target/simple-spring-boot-pac4j-demos-*.jar /build/app.jar

# Runtime stage: JRE only, the fat jar and the baked-in federation metadata.
# metadata/rpfede.jwks (federation signing key, kid "myrpfede") must stay stable
# because the CAS trust anchor pins it in subordinates/rp.json.
# metadata/rpoidc.jwks is (re)generated by pac4j at startup (excluded via .dockerignore).
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /build/app.jar app.jar
COPY metadata ./metadata
COPY docker/entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["./entrypoint.sh"]
